### ISSUE TITLE
Question about how to parcel Neurosynth activation map

### ISSUE THREAD

**Issue by HusBunia** [netneurolab/hansen_genescognition#1]
Hi: 

I have read your paper, but I'm confused about the method "The coordinates reported by Neurosynth were parcellated into 111 left hemisphere cortical regions. "  I guess it is not a simply overlapping between two images. 
Could you please provide some more details about the parcel procedure? 

Thanks!

**Comment by justinehansen** [comment]
Hello,

Thanks for your question! Association maps were created using the [neurosynth repository](https://github.com/neurosynth/neurosynth) and volumetric images were then parcellated according to the Lausanne atlas. Then, only the left hemisphere cortical nodes were retained for analyses. [This](https://github.com/netneurolab/ipn-summer-school/tree/main/lectures/2021-07-02/13-15) folder has a script and a notebook on how to create and parcellate these neurosynth maps (although note this code parcellates it according to the Schaefer atlas).

Hope that helps,

Justine

**Comment by HusBunia** [comment]
> Hello,
> 
> Thanks for your question! Association maps were created using the [neurosynth repository](https://github.com/neurosynth/neurosynth) and volumetric images were then parcellated according to the Lausanne atlas. Then, only the left hemisphere cortical nodes were retained for analyses. [This](https://github.com/netneurolab/ipn-summer-school/tree/main/lectures/2021-07-02/13-15) folder has a script and a notebook on how to create and parcellate these neurosynth maps (although note this code parcellates it according to the Schaefer atlas).
> 
> Hope that helps,
> 
> Justine
I'm sorry for the late reply. Many thanks for your help!  I've found the details in your answer  ^_^
