### ISSUE TITLE
BrainSpan amount of regions

### ISSUE THREAD

**Issue by Melissa1909** [netneurolab/hansen_genescognition#4]
Dear @justinehansen,
thank you for providing this nicely documented and understandable repo! 
I have one (general) question regarding the BrainSpan regions. How did you create mapping.mat, is it based on manually matching anatomical labels? I am also confused that the (adult) 34 DK regions are assigned to 16 regions of BrainSpan, although you then use 12 cortical regions in adults for subsequent analyses. Could you maybe elaborate on this further? Thank you in advance!
Best, Melissa

**Comment by justinehansen** [comment]
Hi Melissa,

The mapping between 16 brainspan regions and 34 DK regions was done manually. Only the fetal stage has 16 regions with gene expression estimates, the other life stages have 12 (line 112 onwards in scpt_brainspan.m will get you the regions with gene exp samples at each life stage, also see "Robustness analysis using BrainSpan" in the Methods section of the paper).

Hope that helps!
Justine

**Comment by Melissa1909** [comment]
Hi Justine,
yes, I saw this section of the code. What I meant is: if I map back the 12 regions in the "regionsIncluded" for adults to the Desikan-Killiany atlas, only 23 of 34 DK-regions match with the 12 included regions, the other regions are dropped because they were assigned to the 4 regions only present in the fetal BrainSpan atlas. 

So if I map back the 16 regions to 34 DK for adults, I actually end up with 12 regions that do not cover the whole cortex, but just 23 DK regions. Is that correct?
Best, Melissa

**Comment by justinehansen** [comment]
Hi Melissa,

Yes that's correct: every region in the 34-region DK atlas was assigned as a subregion of one of the 16, which does mean that if you map the 12 brainspan regions back to the 34-region DK atlas, you won't end up with full coverage (DK subregions of 4 brainspan regions will be absent). 

Best,
Justine
