### ISSUE TITLE
PLSC for brain imaging data

### ISSUE THREAD

**Issue by raywell627** [netneurolab/hansen_genescognition#5]
Hi, 

Thank you for providing such well-documented scripts! 
I have been running the scripts on my own dataset and would like to explore the correlation between gene expression and regional morphology. Would it be appropriate to replace the Neurosynth 125 term maps with the morphometry maps from my 200 subjects, or alternatively, use a group mean morphometry map in place of the Neurosynth matrix?

I would greatly appreciate any advice or guidance you could offer.

**Comment by justinehansen** [comment]
Hi,

I recommend regenerating the gene expression matrix as there are updated default settings in [abagen](https://abagen.readthedocs.io/en/stable/) which would result in better gene expression estimates. Also, to run the PLS you'll need the same observations (in my case, brain regions) in both matrices, so your morphometry maps and the gene expression matrix need to be defined in the same space/parcellation.
